var Player = function(name, goals, assists, position) {
		 this.name = name;
		 this.goals = 0;
		 this.assists= 0;
		 this.position = position;
		 this.points= this.goals + this.assists;
		}
var Vey = new Player ("Linden Vey",9,13, "R"),
		Kassian = new Player("Zack Kassian", 10,6,"R"),
		SedinD = new Player ("Daniel Sedin", 14,46,"L"), 
		SedinH = new Player ("Henrik Sedin", 15,45, "C"),
		Vrbata = new Player ("Radin Vrbata", 26,23, "R"),
		Higgings= new Player ("Chris Higgins",9,21, "L"),
		Hansen= new Player ("Jannik Hansen",14,16, "R"),
		Bonino=new Player ("Nick Bonino", 12,18,"C"),
		Burrows = new Player ("Alexandre Burrows", 14,13,"R"),
		Matthias = new Player ("Shawn Matthias", 17,9,"C"),
		Dorsett = new Player ("Derek Dorsett", 6,17,"R"),
		Richardson = new Player("Brad Richardson", 8,13, "R"),
		Horvat = new Player ("Bo Horvat", 11,10, "C"),
		Edler = new Player ("Alexander Edler", 6,13, "D"),
		Hamhuis = new Player ("Dan Hamhuis", 0, 17, "D"),
		Tanev = new Player("Christopher Tanev", 2,13, "D"),
		Weber = new Player("Yannick Weber", 6,8,"D"),
		Stanton = new Player ("Ryan Stanton", 3,8, "D"),
		Kenins = new Player ("Ronalds Kenins", 3,8, "L"),
		Bieska = new Player ("Kevin Bieska", 3,7,"D"),
		Sbisa = new Player ("Luca Sbisa", 3,7, "D"),
		Clendneing = new Player ("Adam Clendneing", 0,2 "D");